version: '3.1'

services:
#  db:
#    container_name: database
#    image: sameersbn/postgresql:10-2
#    environment:
#      PGPASSWORD: $DB_PASS
#    restart: always
#    ports:
#      - 5432:5432
#    networks:
#      - botnet
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
#    depends_on:
#      - db
    volumes:
      - .:/src


networks:
  botnet:
    driver: bridge